// Apimo returns property amenities (features) from its `property_service`
// catalog in English only. This table localises the most common ones to
// French; anything not listed falls back to the original (English) label.

const AMENITY_FR: Record<string, string> = {
  "Internet": "Internet",
  "Fireplace": "Cheminée",
  "Disabled access": "Accès handicapé",
  "Air-conditioning": "Climatisation",
  "Reversible air-conditioning": "Climatisation réversible",
  "Double glazing": "Double vitrage",
  "Sliding windows": "Baies vitrées coulissantes",
  "Crawl space": "Vide sanitaire",
  "Electric shutters": "Volets électriques",
  "Irrigation sprinkler": "Arrosage automatique",
  "Fence": "Clôture",
  "Outdoor lighting": "Éclairage extérieur",
  "Well drilling": "Forage",
  "Borehole": "Forage",
  "Alarm system": "Système d'alarme",
  "Alarm": "Alarme",
  "Caretaker": "Gardien",
  "Caretaker's house": "Maison de gardien",
  "Intercom": "Interphone",
  "Electric gate": "Portail électrique",
  "Automatic gate": "Portail automatique",
  "Security door": "Porte blindée",
  "Video security": "Vidéosurveillance",
  "Videophone": "Visiophone",
  "Swimming pool": "Piscine",
  "Heated swimming pool": "Piscine chauffée",
  "Heated pool": "Piscine chauffée",
  "Sauna": "Sauna",
  "Spa": "Spa",
  "Jacuzzi": "Jacuzzi",
  "Tennis court": "Court de tennis",
  "Garage": "Garage",
  "Parking": "Parking",
  "Cellar": "Cave",
  "Wine cellar": "Cave à vin",
  "Lift": "Ascenseur",
  "Elevator": "Ascenseur",
  "Terrace": "Terrasse",
  "Balcony": "Balcon",
  "Garden": "Jardin",
  "Sea view": "Vue mer",
  "Home automation": "Domotique",
  "Pool house": "Pool house",
  "Gym": "Salle de sport",
  "Fitness": "Salle de fitness",
  "Underfloor heating": "Chauffage au sol",
  "Solar panels": "Panneaux solaires",
  "Pétanque court": "Terrain de pétanque",
  "Boules pitch": "Terrain de pétanque",
  "Double-glazing": "Double vitrage",
  "Air conditioning": "Climatisation",
  "Storeroom": "Débarras",
  "Laundry room": "Buanderie",
  "Dressing room": "Dressing",
  "Pantry": "Cellier",
  "Workshop": "Atelier",
  "Attic": "Combles",
  "Basement": "Sous-sol",
  "Veranda": "Véranda",
  "Outbuilding": "Dépendance",
  "Barbecue": "Barbecue",
  "Summer kitchen": "Cuisine d'été",
  "Optic fiber": "Fibre optique",
  "Optical fiber": "Fibre optique",
  "Mosquito net": "Moustiquaires",
  "Watering": "Arrosage",
  "Electric heating": "Chauffage électrique",
  "Gas heating": "Chauffage au gaz",
  "Central heating": "Chauffage central",
  "Heat pump": "Pompe à chaleur",
};

const AMENITY_NL: Record<string, string> = {
  "Internet": "Internet",
  "Fireplace": "Open haard",
  "Disabled access": "Rolstoeltoegankelijk",
  "Air-conditioning": "Airconditioning",
  "Reversible air-conditioning": "Omkeerbare airconditioning",
  "Double glazing": "Dubbele beglazing",
  "Sliding windows": "Schuifpuien",
  "Crawl space": "Kruipruimte",
  "Electric shutters": "Elektrische rolluiken",
  "Irrigation sprinkler": "Automatische beregening",
  "Fence": "Omheining",
  "Outdoor lighting": "Buitenverlichting",
  "Well drilling": "Waterput",
  "Borehole": "Waterput",
  "Alarm system": "Alarmsysteem",
  "Alarm": "Alarm",
  "Caretaker": "Conciërge",
  "Caretaker's house": "Conciërgewoning",
  "Intercom": "Intercom",
  "Electric gate": "Elektrisch hek",
  "Automatic gate": "Automatisch hek",
  "Security door": "Beveiligde deur",
  "Video security": "Videobewaking",
  "Videophone": "Video-intercom",
  "Swimming pool": "Zwembad",
  "Heated swimming pool": "Verwarmd zwembad",
  "Heated pool": "Verwarmd zwembad",
  "Sauna": "Sauna",
  "Spa": "Spa",
  "Jacuzzi": "Jacuzzi",
  "Tennis court": "Tennisbaan",
  "Garage": "Garage",
  "Parking": "Parkeerplaats",
  "Cellar": "Kelder",
  "Wine cellar": "Wijnkelder",
  "Lift": "Lift",
  "Elevator": "Lift",
  "Terrace": "Terras",
  "Balcony": "Balkon",
  "Garden": "Tuin",
  "Sea view": "Zeezicht",
  "Home automation": "Domotica",
  "Pool house": "Poolhouse",
  "Gym": "Fitnessruimte",
  "Fitness": "Fitnessruimte",
  "Underfloor heating": "Vloerverwarming",
  "Solar panels": "Zonnepanelen",
  "Pétanque court": "Jeu-de-boulesbaan",
  "Boules pitch": "Jeu-de-boulesbaan",
  "Double-glazing": "Dubbele beglazing",
  "Air conditioning": "Airconditioning",
  "Storeroom": "Berging",
  "Laundry room": "Bijkeuken",
  "Dressing room": "Inloopkast",
  "Pantry": "Provisiekast",
  "Workshop": "Werkplaats",
  "Attic": "Zolder",
  "Basement": "Souterrain",
  "Veranda": "Veranda",
  "Outbuilding": "Bijgebouw",
  "Barbecue": "Barbecue",
  "Summer kitchen": "Zomerkeuken",
  "Optic fiber": "Glasvezel",
  "Optical fiber": "Glasvezel",
  "Mosquito net": "Horren",
  "Watering": "Beregening",
  "Electric heating": "Elektrische verwarming",
  "Gas heating": "Gasverwarming",
  "Central heating": "Centrale verwarming",
  "Heat pump": "Warmtepomp",
};

/** Translate an Apimo amenity to French or Dutch; English used as fallback. */
export function localizeFeature(
  name: string,
  lang: "fr" | "en" | "nl",
): string {
  if (lang === "en") return name;
  if (lang === "nl") return AMENITY_NL[name] ?? name;
  return AMENITY_FR[name] ?? name;
}
