// Apimo returns property amenities (features) from its `property_service`
// catalog in English only. This table localises the most common ones to
// French; anything not listed falls back to the original (English) label.

const AMENITY_FR: Record<string, string> = {
  "Internet": "Internet",
  "Fireplace": "Cheminée",
  "Disabled access": "Accès handicapé",
  "Air-conditioning": "Climatisation",
  "Reversible air-conditioning": "Climatisation réversible",
  "Double glazing": "Double vitrage",
  "Sliding windows": "Baies vitrées coulissantes",
  "Crawl space": "Vide sanitaire",
  "Electric shutters": "Volets électriques",
  "Irrigation sprinkler": "Arrosage automatique",
  "Fence": "Clôture",
  "Outdoor lighting": "Éclairage extérieur",
  "Well drilling": "Forage",
  "Borehole": "Forage",
  "Alarm system": "Système d'alarme",
  "Alarm": "Alarme",
  "Caretaker": "Gardien",
  "Caretaker's house": "Maison de gardien",
  "Intercom": "Interphone",
  "Electric gate": "Portail électrique",
  "Automatic gate": "Portail automatique",
  "Security door": "Porte blindée",
  "Video security": "Vidéosurveillance",
  "Videophone": "Visiophone",
  "Swimming pool": "Piscine",
  "Heated swimming pool": "Piscine chauffée",
  "Heated pool": "Piscine chauffée",
  "Sauna": "Sauna",
  "Spa": "Spa",
  "Jacuzzi": "Jacuzzi",
  "Tennis court": "Court de tennis",
  "Garage": "Garage",
  "Parking": "Parking",
  "Cellar": "Cave",
  "Wine cellar": "Cave à vin",
  "Lift": "Ascenseur",
  "Elevator": "Ascenseur",
  "Terrace": "Terrasse",
  "Balcony": "Balcon",
  "Garden": "Jardin",
  "Sea view": "Vue mer",
  "Home automation": "Domotique",
  "Pool house": "Pool house",
  "Gym": "Salle de sport",
  "Fitness": "Salle de fitness",
  "Underfloor heating": "Chauffage au sol",
  "Solar panels": "Panneaux solaires",
  "Pétanque court": "Terrain de pétanque",
  "Boules pitch": "Terrain de pétanque",
  "Double-glazing": "Double vitrage",
  "Air conditioning": "Climatisation",
  "Storeroom": "Débarras",
  "Laundry room": "Buanderie",
  "Dressing room": "Dressing",
  "Pantry": "Cellier",
  "Workshop": "Atelier",
  "Attic": "Combles",
  "Basement": "Sous-sol",
  "Veranda": "Véranda",
  "Outbuilding": "Dépendance",
  "Barbecue": "Barbecue",
  "Summer kitchen": "Cuisine d'été",
  "Optic fiber": "Fibre optique",
  "Optical fiber": "Fibre optique",
  "Mosquito net": "Moustiquaires",
  "Watering": "Arrosage",
  "Electric heating": "Chauffage électrique",
  "Gas heating": "Chauffage au gaz",
  "Central heating": "Chauffage central",
  "Heat pump": "Pompe à chaleur",
};

/** Translate an Apimo amenity to French; English used elsewhere / as fallback. */
export function localizeFeature(name: string, lang: "fr" | "en"): string {
  if (lang === "en") return name;
  return AMENITY_FR[name] ?? name;
}
